-- Create custom types for H2 to support JSONB
CREATE DOMAIN IF NOT EXISTS JSONB AS CLOB;

-- Create properties table with JSONB support
CREATE TABLE IF NOT EXISTS properties (
    property_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_title VARCHAR(150),
    description VARCHAR(500),
    property_type VARCHAR(50),
    address_line1 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    pincode VARCHAR(10),
    latitude DOUBLE,
    longitude DOUBLE,
    host_id BIGINT,
    host_name VARCHAR(100),
    host_contact VARCHAR(15),
    host_email VARCHAR(100),
    base_price DOUBLE,
    currency VARCHAR(3),
    amenities JSONB,
    image_url VARCHAR(500),
    status VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Create upload_audit table with JSONB support
CREATE TABLE IF NOT EXISTS upload_audit (
    upload_id UUID PRIMARY KEY,
    file_name VARCHAR(255),
    uploaded_by VARCHAR(255),
    timestamp TIMESTAMP,
    status VARCHAR(255) CHECK (status IN ('PROCESSING','COMPLETED','FAILED')),
    row_results JSONB,
    total_rows INTEGER,
    success_rows INTEGER,
    failed_rows INTEGER,
    warning_rows INTEGER
);
